# Generated by Django 5.0.6 on 2024-05-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['name'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['sort'], 'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='about',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='about',
            name='sort',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sort',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team'),
        ),
        migrations.AddField(
            model_name='team',
            name='sort',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='sort',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
